version: 2.1
jobs:
  build:
    working_directory: ~/matsudamper/PreviewRecyclerView
    docker:
      - image: circleci/android:api-28
    environment:
      #      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      #      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      GRADLE_OPTS: -Xmx4000m -Xms4000m -XX:MaxPermSize=4000m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dorg.gradle.caching=true
      ANDROID_HOST: /usr/local/android-sdk-linux
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - checkout

      # Dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "lib/build.gradle" }}

      # build
      - run:
          name: build app
          command: ./gradlew build
      #          command: ./gradlew :app:assembleDebug

      # save
      - store_artifacts:
          path: $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: app/build/outputs/apk/
      - store_artifacts:
          path: $CIRCLE_TEST_REPORTS

      # test
      - run:
          name: test
          command: ./gradlew test